Add messages table
Groupyz/Messages_api pull request #14
Opened 2023-05-09 18:29 UTC by StavTasa

2023-05-09 20:28 UTC, ndvisme commented on .vscode/settings.json
@StavTasa please delete duplicate line.

2023-05-09 20:42 UTC, ndvisme commented on app/DB/models.py
@StavTasa a few changes here are needed:
1) Make repeat column to picklist value (meaning it can receive only specific types of values)
2) Change 'time_to_send' column to a 'Datetime' type
3) 'Message title' must have a value? why?
4) Make the 'message_data' capacity to a higher value, maybe 500 chars?

2023-05-09 20:45 UTC, ndvisme requested changes
@StavTasa hey, all in all looks good. 
Good job. 
Just a few changes are needed (written in the comments)

2023-05-11 05:33 UTC, StavTasa commented on .vscode/settings.json
@ndvisme done

2023-05-12 21:42 UTC, ndvisme commented on app/DB/models.py
@StavTasa  repeat looks good.
Time to send is still a string, please change this.

2023-05-12 21:47 UTC, ndvisme commented on app/tests/test_db.py
@StavTasa, I see that we use the 'id' field a few different lines of code (id=1234), please make it a variable (DUMMY_MESSAGE_ID = 1234, or something similar). The reason for this request is so if in the future this will be changed, it will be done in one place & not in 4.

2023-05-14 15:40 UTC, ndvisme approved these changes
@StavTasa, looks great. Thanks for he changes. Checking it now!

2023-05-14 15:41 UTC, merged